apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/helm-default: "true"
        io.kompose.service: api
    spec:
      containers:
        - args:
            - start
            - api
            - --production
            - --port
            - "8000"
          env:
            - name: MRSM_CONFIG
              value: |-
                {
                    "meerschaum": {
                      "instance": "sql:local",
                      "api_instance": "sql:local",
                      "web_instance": "sql:local"
                    }
                }
          image: bmeares/meerschaum:api
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:8000/healthcheck
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 3
          name: api
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /meerschaum
              name: api-root
      hostname: api
      restartPolicy: Always
      volumes:
        - name: api-root
          persistentVolumeClaim:
            claimName: api-root
status: {}
