{{- if .Values.ingress.enabled -}}
{{- $svcPort := .Values.service.port -}}
{{- $fullName := include "meerschaum.fullname" . -}}
apiVersion: {{ template "meerschaum.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "meerschaum.fullname" . }}
  labels:
    {{- include "meerschaum.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
      {{- range .Values.ingress.hosts }}
      - {{ . | quote }}
      {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
  {{- end }}
{{- end }}
