name: meerschaum
description: A Meerschaum Helm chart.
app.kubernetes.io/managed-by: "Helm"
meta.helm.sh/release-name: "meerschaum"
meta.helm.sh/release-namespace: "default"
type: application
version: 0.0.1
appVersion: 2.0.4
apiVersion: v2
keywords:
  - meerschaum
  - mrsm
